export const MOROCCAN_CITIES = [
    { name: "Casablanca", arabicName: "الدار البيضاء" },
    { name: "Rabat", arabicName: "الرباط" },
    { name: "Marrakech", arabicName: "مراكش" },
    { name: "Fès", arabicName: "فاس" },
    { name: "Tanger", arabicName: "طنجة" },
    { name: "Agadir", arabicName: "أكادير" },
    { name: "Meknès", arabicName: "مكناس" },
    { name: "Oujda", arabicName: "وجدة" },
    { name: "Kenitra", arabicName: "القنيطرة" },
    { name: "Tetouan", arabicName: "تطوان" },
    { name: "Safi", arabicName: "آسفي" },
    { name: "Temara", arabicName: "تمارة" },
    { name: "Inezgane", arabicName: "أنزكان" },
    { name: "Mohammedia", arabicName: "المحمدية" },
    { name: "Laayoune", arabicName: "العيون" },
    { name: "Khouribga", arabicName: "خريبكة" },
    { name: "Beni Mellal", arabicName: "بني ملال" },
    { name: "El Jadida", arabicName: "الجديدة" },
    { name: "Taza", arabicName: "تازة" },
    { name: "Nador", arabicName: "الناظور" },
    { name: "Settat", arabicName: "سطات" },
    { name: "Ksar El Kebir", arabicName: "القصر الكبير" },
    { name: "Larache", arabicName: "العرائش" },
    { name: "Khemisset", arabicName: "الخميسات" },
    { name: "Guelmim", arabicName: "كلميم" },
    { name: "Berrechid", arabicName: "برشيد" },
    { name: "Oued Zem", arabicName: "واد زم" },
    { name: "Fquih Ben Salah", arabicName: "الفقيه بن صالح" },
    { name: "Taourirt", arabicName: "تاوريرت" },
    { name: "Berkane", arabicName: "بركان" },
    { name: "Sidi Slimane", arabicName: "سيدي سليمان" },
    { name: "El Kelaa des Sraghna", arabicName: "قلعة السراغنة" },
    { name: "Taroudant", arabicName: "تارودانت" },
    { name: "Chefchaouen", arabicName: "شفشاون" },
    { name: "Essaouira", arabicName: "الصويرة" },
    { name: "Tiznit", arabicName: "تيزنيت" },
    { name: "Ouarzazate", arabicName: "ورززات" },
    { name: "Al Hoceima", arabicName: "الحسيمة" },
    { name: "Erfoud", arabicName: "إرفود" },
    { name: "Midelt", arabicName: "ميدلت" }
].sort((a, b) => a.name.localeCompare(b.name));
